#:schema node_modules/wrangler/config-schema.json
name = "tiddlyflare-env_unspecified"
main = "src/index.ts"
compatibility_date = "2024-09-25"

assets = { directory = "./public/", binding = "ASSETS" }

# Retain dashboard changes during deployments for variable changes!
keep_vars = true

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

#######################################################
## DEV
#######################################################

[env.dev]
name = "tiddlyflare-dev"

[env.dev.vars]
VAR_API_AUTH_ENABLED = true

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[env.dev.durable_objects]
bindings = [
    {name = "TENANT", class_name = "TenantDO"},
    {name = "WIKI", class_name = "WikiDO"},
]

#######################################################
## STAGING
#######################################################

[env.staging]
name = "tiddlyflare-staging"
routes = [
    { pattern = "tiddly-staging.kevinkipp.com", custom_domain = true },
]

[env.staging.vars]
VAR_API_AUTH_ENABLED = true
# Put it in `.dev.vars` when running locally.
# https://developers.cloudflare.com/workers/wrangler/configuration/#secrets
#VAR_API_AUTH_ADMIN_KEYS_CSV = ",rf_key_TENANT1111_sometoken,"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[env.staging.durable_objects]
bindings = [
    {name = "TENANT", class_name = "TenantDO"},
    {name = "WIKI", class_name = "WikiDO"},
]

#######################################################
## PROD
#######################################################

[env.prod]
name = "tiddlyflare-prod"
routes = [
    { pattern = "tiddly.kevinkipp.com", custom_domain = true },
]

[env.prod.vars]
VAR_API_AUTH_ENABLED = true
# Put it in `.dev.vars` when running locally.
# https://developers.cloudflare.com/workers/wrangler/configuration/#secrets
#VAR_API_AUTH_ADMIN_KEYS_CSV = ",rf_key_TENANT1111_sometoken,"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[env.prod.durable_objects]
bindings = [
    {name = "TENANT", class_name = "TenantDO"},
    {name = "WIKI", class_name = "WikiDO"},
]

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["TenantDO", "WikiDO"]
